### ISSUE TITLE
`useGroup` causes odd comma placement

### ISSUE THREAD

**Issue by yarnball** [IceEnd/react-count-animation#4]
Hi,

Firstly- great work on this. Very easy to use, and great options to change the animations.

I seem to have found a potential bug. When `useGroup` is true, and the number is below `-100,000` it displays the number as `-,100,000`.

As a positive number, it works fine (eg `100,000`)

Any ideas on a fix?

Thanks

**Comment by IceEnd** [comment]
Hey, I have fixed this bug.
 [@v1.1.3](https://www.npmjs.com/package/react-count-animation).

**Comment by yarnball** [comment]
Thanks, but the bug still seems to be present in 1.1.3 (@latest). Could you confirm it is fixed?

**Comment by IceEnd** [comment]
I have confirm it.

There is example:
```javascript
const settings = {
    start: 99923,
    count: -100000,
    duration: 3000,
    decimals: 4,
    useGroup: true,
    animation: 'slide',
};
```
It works for me. 
Can you show me the code? And I can debug.

**Comment by yarnball** [comment]
All good- I double checked. Thanks for that. Really like this project. Would be cool to see more such as for animating lists and text
